_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 63
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 63
            "3":
                - 2
                - 3
                - 16
                - 55
            "4": 3.10.18
            "5": 0.20.1
            "6": 4.53.0
            "8":
                - 1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 32
early_stop_threshold:
    value: 0.001
epochs:
    value: 50
learning_rate:
    value: 0.0001
model:
    value: ResNet50
patience:
    value: 2
